{- -*- Mode: haskell; -*-
Haskell Magic Interface
Copyright (C) 2005 John Goerzen <jgoerzen@complete.org>

This code is under a 3-clause BSD license; see COPYING for details.
-}

{-
This generator produces src/Magic/Data.hsc: the MagicFlags newtype (a bit-mask
over the C @MAGIC_*@ constants in <magic.h>) with a Monoid interface, a Show
that prints set flags by name, and a pattern synonym for each flag.

To regenerate after adding (or removing) a flag:

    runghc utils/genconsts.hs > src/Magic/Data.hsc

Keep both lists below in sync with <magic.h>: `magicFlags` (the constants to
emit, in order) and `flagDocs` (the Haddock description for each). A constant
missing from `flagDocs` still generates, with a placeholder description.
-}

import Data.Char
import Data.List

const2HS (x:xs) =
    x : c2hs xs
    where c2hs [] = []
          c2hs ('_':x:xs) = x : c2hs xs
          c2hs (x:xs) = toLower x : c2hs xs

getC const = "#{const " ++ const ++ "}"

-- | Haddock description for each MAGIC_* constant.
flagDocs :: [(String, String)]
flagDocs =
  [ ("MAGIC_NONE",           "No special handling; return a textual description (the default). This is 'mempty'.")
  , ("MAGIC_DEBUG",          "Print debugging messages to stderr.")
  , ("MAGIC_SYMLINK",        "Follow symbolic links.")
  , ("MAGIC_COMPRESS",       "Look inside compressed files.")
  , ("MAGIC_DEVICES",        "Look at the contents of block or character special devices.")
  , ("MAGIC_MIME_TYPE",      "Return a MIME type string instead of a textual description.")
  , ("MAGIC_MIME_ENCODING",  "Return the MIME encoding (character set) instead of a textual description.")
  , ("MAGIC_MIME",           "Return both the MIME type and the encoding (@'MagicMimeType' '<>' 'MagicMimeEncoding'@).")
  , ("MAGIC_CONTINUE",       "Return all matches, not just the first.")
  , ("MAGIC_CHECK",          "Check the magic database for consistency and report problems.")
  , ("MAGIC_PRESERVE_ATIME", "Preserve the access time of examined files.")
  , ("MAGIC_RAW",            "Do not translate unprintable characters to octal escapes.")
  , ("MAGIC_ERROR",          "Treat errors while examining a file as real errors instead of embedding them in the result.")
  , ("MAGIC_APPLE",          "Return the Apple creator and type.")
  , ("MAGIC_EXTENSION",      "Return a slash-separated list of valid file extensions for the detected type.")
  , ("MAGIC_COMPRESS_TRANSP","Report on the compressed contents only, without mentioning the compression itself (transparent decompression).")
  , ("MAGIC_NO_COMPRESS_FORK","Do not allow decompression that requires forking a helper process.")
  , ("MAGIC_NODESC",         "Composite of 'MagicExtension', 'MagicMime' and 'MagicApple': return identifiers rather than a textual description.")
  , ("MAGIC_NO_CHECK_COMPRESS","Do not look inside compressed files.")
  , ("MAGIC_NO_CHECK_TAR",   "Do not examine tar archives.")
  , ("MAGIC_NO_CHECK_SOFT",  "Do not consult the magic database entries (soft magic).")
  , ("MAGIC_NO_CHECK_APPTYPE","Do not check for an application type (e.g. EMX).")
  , ("MAGIC_NO_CHECK_ELF",   "Do not examine ELF details.")
  , ("MAGIC_NO_CHECK_TEXT",  "Do not examine text files.")
  , ("MAGIC_NO_CHECK_CDF",   "Do not examine CDF (Microsoft Compound Document) files.")
  , ("MAGIC_NO_CHECK_CSV",   "Do not examine CSV files.")
  , ("MAGIC_NO_CHECK_TOKENS","Do not look for known text tokens.")
  , ("MAGIC_NO_CHECK_ENCODING","Do not check text encodings.")
  , ("MAGIC_NO_CHECK_JSON",  "Do not examine JSON files.")
  , ("MAGIC_NO_CHECK_SIMH",  "Do not examine SIMH tape files.")
  , ("MAGIC_NO_CHECK_BUILTIN","Disable all built-in tests; consult only the magic database.")
  ]

docFor :: String -> String
docFor c = maybe ("The " ++ c ++ " flag.") id (lookup c flagDocs)

-- The fixed top of the module: pragmas, header, the MagicFlags newtype, its
-- Monoid/Semigroup instances, hasFlag, removeFlags, and a name-printing Show.
-- The per-flag pattern synonyms and the allNamedFlags table are generated from
-- `magicFlags`.
header consts =
 "-- AUTO-GENERATED FILE, DO NOT EDIT.  GENERATED BY utils/genconsts.hs\n" ++
 "{-# LANGUAGE DeriveGeneric #-}\n" ++
 "{-# LANGUAGE PatternSynonyms #-}\n" ++
 "{- |\n" ++
 "   Module     : Magic.Data\n" ++
 "   Copyright  : Copyright (C) 2005 John Goerzen\n" ++
 "   License    : BSD-3-Clause\n" ++
 "\n" ++
 "   Maintainer : Philippe <philippedev101\\@gmail.com>\n" ++
 "   Stability  : provisional\n" ++
 "   Portability: portable\n" ++
 "\n" ++
 "The t'MagicFlags' bit-mask, mapping the C @libmagic@ @MAGIC_*@ constants to\n" ++
 "Haskell. Flags are combined with @('<>')@, tested with 'hasFlag', and narrowed\n" ++
 "with 'removeFlags'; the empty set ('mempty') is 'MagicNone'.\n" ++
 "-}\n\n" ++
 "module Magic.Data\n" ++
 "  ( MagicFlags(..)\n" ++
 "  , hasFlag\n" ++
 "  , removeFlags\n" ++
 concatMap (\c -> "  , pattern " ++ const2HS c ++ "\n") consts ++
 "  ) where\n" ++
 "\n#include \"magic.h\"\n\n" ++
 "import Control.DeepSeq (NFData(rnf))\n" ++
 "import Data.Bits ((.&.), (.|.), complement, popCount)\n" ++
 "import Data.List (intercalate)\n" ++
 "import Foreign.C.Types (CInt)\n" ++
 "import GHC.Generics (Generic)\n\n" ++
 "-- | A set of @libmagic@ flags, represented as the underlying C bit-mask.\n" ++
 "-- Combine flags with @('<>')@, start from 'mempty' (no flags), test\n" ++
 "-- membership with 'hasFlag', and narrow with 'removeFlags'. The\n" ++
 "-- v'MagicFlags' constructor is an escape hatch for passing a raw mask;\n" ++
 "-- prefer the pattern synonyms below.\n" ++
 "--\n" ++
 "-- @since 2.0.0\n" ++
 "newtype MagicFlags = MagicFlags CInt\n" ++
 "  deriving (Eq, Ord, Generic)\n\n" ++
 "instance NFData MagicFlags where rnf (MagicFlags x) = x `seq` ()\n\n" ++
 "-- | Flags combine by bitwise-or.\n" ++
 "instance Semigroup MagicFlags where\n" ++
 "  MagicFlags a <> MagicFlags b = MagicFlags (a .|. b)\n\n" ++
 "-- | 'mempty' is the empty flag set ('MagicNone').\n" ++
 "instance Monoid MagicFlags where\n" ++
 "  mempty = MagicFlags 0\n\n" ++
 "-- | Prints the set flags by name (e.g. @MagicMimeType <> MagicError@), or\n" ++
 "-- @MagicNone@ when empty. Any bits not corresponding to a known flag are\n" ++
 "-- shown as a raw @MagicFlags n@ term.\n" ++
 "instance Show MagicFlags where\n" ++
 "  showsPrec p fs =\n" ++
 "    case names of\n" ++
 "      []  -> showString \"MagicNone\"\n" ++
 "      [n] -> showString n\n" ++
 "      _   -> showParen (p > 6) (showString (intercalate \" <> \" names))\n" ++
 "    where\n" ++
 "      MagicFlags raw = fs\n" ++
 "      set      = [ (n, v) | (n, MagicFlags v) <- allNamedFlags, popCount v == 1, raw .&. v == v ]\n" ++
 "      covered  = foldr (\\(_, v) acc -> v .|. acc) (0 :: CInt) set\n" ++
 "      leftover = raw .&. complement covered\n" ++
 "      names    = map fst set ++ [ \"MagicFlags \" ++ show leftover | leftover /= (0 :: CInt) ]\n\n" ++
 "-- | @'hasFlag' fs flag@ is 'True' when every bit of @flag@ is set in @fs@.\n" ++
 "-- Works for composite flags too (e.g. @fs \\`hasFlag\\` 'MagicMime'@). Note\n" ++
 "-- that @fs \\`hasFlag\\` 'MagicNone'@ is always 'True' (the empty set is a\n" ++
 "-- subset of everything).\n" ++
 "--\n" ++
 "-- @since 2.0.0\n" ++
 "hasFlag :: MagicFlags -> MagicFlags -> Bool\n" ++
 "hasFlag (MagicFlags x) (MagicFlags m) = x .&. m == m\n\n" ++
 "-- | @'removeFlags' fs drop@ clears every bit of @drop@ from @fs@ (set\n" ++
 "-- difference), e.g. @flags \\`removeFlags\\` 'MagicError'@.\n" ++
 "--\n" ++
 "-- @since 2.0.0\n" ++
 "removeFlags :: MagicFlags -> MagicFlags -> MagicFlags\n" ++
 "removeFlags (MagicFlags a) (MagicFlags b) = MagicFlags (a .&. complement b)\n\n"

patternDecl name c =
    "-- | " ++ docFor c ++ "\n" ++
    "pattern " ++ const2HS c ++ " :: " ++ name ++ "\n" ++
    "pattern " ++ const2HS c ++ " = " ++ name ++ " (" ++ getC c ++ ")\n\n"

-- The lookup table backing the Show instance: every flag name paired with its
-- value. Not exported.
namedFlagsBlock consts =
    "-- Every named flag, used by the 'Show' instance to print flags by name.\n" ++
    "allNamedFlags :: [(String, MagicFlags)]\n" ++
    "allNamedFlags =\n" ++
    "  [ " ++ intercalate "\n  , " (map entry consts) ++ "\n  ]\n"
    where entry c = "(\"" ++ const2HS c ++ "\", " ++ const2HS c ++ ")"

main =
    do putStr (header magicFlags)
       putStr (concatMap (patternDecl "MagicFlags") magicFlags)
       putStr (namedFlagsBlock magicFlags)

-- NOTE: keep these in sync with <magic.h>. Aliases / zero-valued constants are
-- intentionally omitted: MAGIC_NO_CHECK_ASCII is a synonym for
-- MAGIC_NO_CHECK_TEXT, and MAGIC_NO_CHECK_FORTRAN / MAGIC_NO_CHECK_TROFF are
-- deprecated no-ops equal to 0 (i.e. MAGIC_NONE). Composite flags (MAGIC_MIME,
-- MAGIC_NODESC, MAGIC_NO_CHECK_BUILTIN) are kept.
magicFlags = ["MAGIC_NONE", "MAGIC_DEBUG", "MAGIC_SYMLINK",
              "MAGIC_COMPRESS", "MAGIC_DEVICES",
              "MAGIC_MIME_TYPE", "MAGIC_MIME_ENCODING", "MAGIC_MIME",
              "MAGIC_CONTINUE", "MAGIC_CHECK",
              "MAGIC_PRESERVE_ATIME", "MAGIC_RAW", "MAGIC_ERROR",
              "MAGIC_APPLE", "MAGIC_EXTENSION",
              "MAGIC_COMPRESS_TRANSP", "MAGIC_NO_COMPRESS_FORK",
              "MAGIC_NODESC",
              "MAGIC_NO_CHECK_COMPRESS", "MAGIC_NO_CHECK_TAR",
              "MAGIC_NO_CHECK_SOFT", "MAGIC_NO_CHECK_APPTYPE",
              "MAGIC_NO_CHECK_ELF", "MAGIC_NO_CHECK_TEXT",
              "MAGIC_NO_CHECK_CDF", "MAGIC_NO_CHECK_CSV",
              "MAGIC_NO_CHECK_TOKENS", "MAGIC_NO_CHECK_ENCODING",
              "MAGIC_NO_CHECK_JSON", "MAGIC_NO_CHECK_SIMH",
              "MAGIC_NO_CHECK_BUILTIN"]
